config/routes.rb
Rails.application.routes.draw do
  resources :lost_items
  resources :found_items
  resources :reception_desks
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout" }
  root "pages#index"
end

app/models/reception_desk.rb
class ReceptionDesk < ApplicationRecord
  has_many :found_items, dependent: :destroy
  has_many :lost_items, dependent: :destroy

  validates :name, presence: true
  validates :location, presence: true
end

app/controllers/reception_desks_controller.rb
class ReceptionDesksController < ApplicationController
  before_action :set_reception_desk, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /reception_desks
  def index
    @reception_desks = ReceptionDesk.all
  end

  # GET /reception_desks/1
  def show
    @found_items = FoundItem.where(reception_desk_id: params[:id])
    @lost_items = LostItem.where(reception_desk_id: params[:id])
  end

  # GET /reception_desks/new
  def new
    @reception_desk = ReceptionDesk.new
  end

  # GET /reception_desks/1/edit
  def edit
  end

  # POST /reception_desks
  def create
    @reception_desk = ReceptionDesk.new(reception_desk_params)

    if @reception_desk.save
      redirect_to @reception_desk, notice: "Reception desk was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /reception_desks/1
  def update
    if @reception_desk.update(reception_desk_params)
      redirect_to @reception_desk, notice: "Reception desk was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /reception_desks/1
  def destroy
    @reception_desk.destroy!
    redirect_to reception_desks_url, notice: "Reception desk was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_reception_desk
      @reception_desk = ReceptionDesk.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def reception_desk_params
      params.require(:reception_desk).permit(:name, :location)
    end
end

app/helpers/reception_desks_helper.rb
module ReceptionDesksHelper
end

app/views/reception_desks/_form.html.slim
._c-section__content
  ._c-row._c-row--center
    ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
      = form_for @reception_desk do |f|
        ._c-card
          ._c-card__body
            - if @reception_desk.errors.any?
              h3 = "#{pluralize(@reception_desk.errors.count, "error")} prohibited this reception_desk from being saved:"
              ul._c-meta
                - @reception_desk.errors.full_messages.each do |message|
                  li._c-meta__item = message

            ._c-row__col._c-row__col--1-1
              = f.label :name
              br
              = f.text_field :name, :class => "_c-form-control"
            ._c-row__col._c-row__col--1-1
              = f.label :location
              br
              = f.text_field :location, :class => "_c-form-control"
          ._c-card__action = f.submit :class => "_c-btn _c-btn--block"

app/views/reception_desks/edit.html.slim
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 案内所を更新する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', reception_desks_path

app/views/reception_desks/index.html.slim
- provide(:title, '案内所一覧')
section._c-section
  ._c-container
    h2._c-section__title 案内所一覧
    ._c-section__content
      ul._c-navbar
        li._c-navbar__item data-c="navbar__item"
          = link_to '案内所を登録する', new_reception_desk_path

      - @reception_desks.each do |reception_desk|
        ._c-entry
          header._c-entry__header
            h1._c-entry__title
              = link_to reception_desk.name , reception_desk
            ul._c-meta
              li._c-meta__item Location: #{reception_desk.location}

app/views/reception_desks/new.html.slim
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 案内所を登録する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', reception_desks_path

app/views/reception_desks/show.html.slim
section._c-section
  ._c-container
    ._c-section__content
      article._c-entry
        header._c-entry__header
          h1._c-entry__title = @reception_desk.name
          ul._c-meta
            li._c-meta__item Location: #{@reception_desk.location}
        ._c-entry__content
          ul._c-navbar
            li._c-navbar__item data-c="navbar__item" = link_to '更新する', edit_reception_desk_path(@reception_desk)
            li._c-navbar__item data-c="navbar__item" = link_to '案内所一覧', reception_desks_path
          ._c-row._c-row--margin
            ._c-row__col._c-row__col--1-1._c-row__col--md-1-2
              h2._c-section__title._u-text-left 拾得物
              ul._c-navbar
                li._c-navbar__item data-c="navbar__item" = link_to '登録する', new_found_item_path
              ._c-row._c-row--margin
                - unless @found_items.empty?
                  - @found_items.each do |found_item|
                    ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
                      ._c-card
                        ._c-card__body
                          h1 #{found_item.kind_i18n}
                          ul._c-meta
                            li._c-meta__item 拾得場所: #{found_item.location_found}
                          table
                            tbody
                              tr
                                td 案内所
                                td = link_to found_item.reception_desk.name, reception_desk_path(found_item.reception_desk.id)
                              tr
                                td 特徴
                                td = found_item.characteristic
                            p = found_item.note
                        ._c-card__action
                          - if found_item.status?
                            = link_to 'さらに詳しく', found_item, :class => '_c-btn _c-btn--block'
                          - else
                            = link_to 'さらに詳しく', found_item, :class => '_c-btn _c-btn--block _c-btn--danger'
                - else
                  p 登録されていません

            ._c-row__col._c-row__col--1-1._c-row__col--md-1-2
              h2._c-section__title._u-text-left 紛失物
              ul._c-navbar
                li._c-navbar__item data-c="navbar__item" = link_to '登録する', new_lost_item_path
              ._c-row._c-row--margin
                - unless @lost_items.empty?
                  - @lost_items.each do |lost_item|
                    ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
                      ._c-card
                        ._c-card__body
                          h1 #{lost_item.kind_i18n}
                          ul._c-meta
                            li._c-meta__item 紛失場所: #{lost_item.location_lost}
                          table
                            tbody
                              tr
                                td 案内所
                                td = link_to lost_item.reception_desk.name, reception_desk_path(lost_item.reception_desk.id)
                              tr
                                td 特徴
                                td = lost_item.characteristic
                            p = lost_item.note
                        ._c-card__action
                          - if lost_item.status?
                            = link_to 'さらに詳しく', lost_item, :class => '_c-btn _c-btn--block'
                          - else
                            = link_to 'さらに詳しく', lost_item, :class => '_c-btn _c-btn--block _c-btn--danger'
                - else
                  p 登録されていません