config/routes.rb
Rails.application.routes.draw do
  resources :lost_items
  resources :found_items
  resources :reception_desks
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout" }
  root "pages#index"
end

app/models/found_item.rb
class FoundItem < ApplicationRecord
  before_save :set_resolved_at
  belongs_to :reception_desk
  validates :reception_desk_id, presence: true
  validates :receptionist_id, presence: true
  validates :kind, presence: true
  validates :location_found, presence: true
  validates :characteristic, presence: true
  validates :status, inclusion: { in: [true, false] }
  validate :check_resolver_id
  enum kind: {
    other: 0,
    key: 1,
    wallet: 2,
    mobile_phone: 3,
    electronic_device: 4,
    clothes: 5,
    card: 6,
    cash: 7,
    card_case: 8,
    keychain: 9,
    umbrella: 10,
    glasses: 11,
  }

  def set_resolved_at
    self.resolved_at = if status
                         Time.now.utc
                       else
                         ""
                       end
  end

  def check_resolver_id
    if self.status && !self.resolver_id
      errors.add(:resolver_id, "を入力してください")
    end
  end
end

app/controllers/found_items_controller.rb
class FoundItemsController < ApplicationController
  before_action :set_found_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy, :search]

  # GET /found_items
  def index
    @found_item = FoundItem.new
    @search = FoundItem.ransack(params[:q])
    if params[:q]
      characteristics = params[:q][:characteristic_cont_all].split(/[\p{blank}\s]+/) unless params[:q][:characteristic_cont_all].nil?
      params[:q][:characteristic_cont_all] = characteristics if characteristics
      notes = params[:q][:note_cont_all].split(/[\p{blank}\s]+/) unless params[:q][:note_cont_all].nil?
      params[:q][:note_cont_all] = notes if notes
      @search = FoundItem.ransack(params[:q])
      @found_items = @search.result.order(created_at: :desc).page params[:page]
    else
      @found_items = FoundItem.order(created_at: :desc).page params[:page]
    end

    respond_to do |format|
      format.html
      format.csv do
        @found_items = FoundItem.all
        send_data render_to_string, filename: "found_items.csv", type: :csv
      end
    end
  end

  # GET /found_items/1
  def show
  end

  # GET /found_items/new
  def new
    @found_item = FoundItem.new
  end

  # GET /found_items/1/edit
  def edit
  end

  # POST /found_items
  def create
    @found_item = FoundItem.new(found_item_params)

    if @found_item.save
      redirect_to found_items_path, notice: "Found item was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /found_items/1
  def update
    if @found_item.update(found_item_params)
      redirect_to @found_item, notice: "Found item was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /found_items/1
  def destroy
    @found_item.destroy!
    redirect_to found_items_url, notice: "Found item was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_found_item
      @found_item = FoundItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def found_item_params
      params.require(:found_item).permit(:resolver_id, :reception_desk_id,
                                         :receptionist_id, :kind,
                                         :location_found, :characteristic,
                                         :finder_name, :finder_contact,
                                         :note, :status,
                                         :q)
    end
end

app/helpers/found_items_helper.rb
module FoundItemsHelper
end

app/views/found_items/_form.html.slim
._c-section__content
  ._c-row._c-row--center
    ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
      = form_for @found_item do |f|
        ._c-card
          ._c-card__body
            - if @found_item.errors.any?
              ._c-alert._c-alert--danger
                h3 エラー
                ul._c-meta
                  - @found_item.errors.full_messages.each do |message|
                    li._c-meta__item = message


            ._c-row__col._c-row__col--1-1
              = f.label :reception_desk_id
              br
              span._c-select data-c="select" aria-selected="false"
                = f.collection_select :reception_desk_id, ReceptionDesk.all, :id, :name
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :receptionist_id
              br
              span._c-select data-c="select" aria-selected="false"
                - if :receptionist_id.blank?
                  = f.collection_select :receptionist_id, User.all, :id, :name, :selected => current_user.id
                - else
                  = f.collection_select :receptionist_id, User.all, :id, :name
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :kind
              br
              span._c-select data-c="select" aria-selected="false"
                = f.select :kind, FoundItem.kinds_i18n.invert
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :location_found
              br
              = f.text_field :location_found, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :characteristic
              br
              = f.text_field :characteristic, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :finder_name
              br
              = f.text_field :finder_name, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :finder_contact
              br
              = f.text_field :finder_contact, :class => "_c-form-control"
            ._c-row__col._c-row__col--1-1
              = f.label :note
              br
              = f.text_area :note, :class => "_c-form-control"
            hr
            ._c-row__col._c-row__col--1-1
              = f.label :resolver_id
              br
              small 未解決の場合は空白を選択してください。
              br
              span._c-select data-c="select" aria-selected="false"
                = f.collection_select :resolver_id, User.all, :id, :name, :include_blank => true
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :status
              br
              label
                span._c-radio>
                  = f.radio_button :status, true
                  span._c-radio__control
                | 解決済み
              label
                span._c-radio>
                  = f.radio_button :status, false
                  span._c-radio__control
                | 未解決
          ._c-card__action
            = f.submit :class => "_c-btn _c-btn--block"

app/views/found_items/edit.html.slim
- provide(:title, '拾得物を編集する')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 拾得物を編集する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', found_items_path

app/views/found_items/index.html.slim
- provide(:title, '拾得物')
section._c-section
  ._c-container
    h2._c-section__title 拾得物を登録する
    == render 'form'
section._c-section
  ._c-container
    h2._c-section__title 拾得物検索
    ._c-section__content
      ._c-row._c-row--center
        ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
          = search_form_for @search, url: found_items_path do |f|
            ._c-card
              ._c-card__body
                ._c-row__col._c-row__col--1-1
                  = f.label :status_eq, "状態"
                  br
                  label
                    span._c-radio>
                      = f.radio_button :status_eq, true
                      span._c-radio__control
                    | 解決済み
                  label
                    span._c-radio>
                      = f.radio_button :status_eq, false
                      span._c-radio__control
                    | 未解決
                ._c-row__col._c-row__col--1-1
                  = f.label :reception_desk_id_eq, "受付案内所"
                  br
                    span._c-select data-c="select" aria-selected="false"
                      = f.collection_select :reception_desk_id_eq, ReceptionDesk.all, :id, :name, :include_blank => true
                      span._c-select__label data-c="select__label"
                ._c-row__col._c-row__col--1-1
                  = f.label :kind_eq, "種別"
                  br
                  span._c-select data-c="select" aria-selected="false"
                    = f.select :kind_eq, FoundItem.kinds_i18n.invert.map {|key, value| [key, FoundItem.kinds[value]]}, :include_blank => true
                    span._c-select__label data-c="select__label"
                ._c-row__col._c-row__col--1-1
                  = f.label :characteristic_cont_all, "特徴"
                  br
                    = f.search_field :characteristic_cont_all, :class => '_c-form-control'
                ._c-row__col._c-row__col--1-1
                  = f.label :note_cont_all, "備考"
                  br
                    = f.search_field :note_cont_all, :class => '_c-form-control'
              ._c-card__action
                = f.submit '検索', :class => "_c-btn _c-btn--block"
section._c-section
  ._c-container
    h2._c-section__title 拾得物一覧
    ._c-section__content
      ul._c-meta
      - unless @found_items.total_count == 0
        li._c-meta__item #{@found_items.total_count}件の拾得物情報が見つかりました。
        li._c-meta__item = link_to "CSVダウンロード", found_items_path(format: "csv")
      - else
        li._c-meta__item 拾得物情報が見つかりませんでした。
      ._c-row._c-row--margin
        - @found_items.each do |found_item|
          ._c-row__col._c-row__col--1-1._c-row__col--md-1-2._c-row__col--lg-1-4
            ._c-card
              ._c-card__body
                h1 #{found_item.kind_i18n}
                small 拾得場所 #{found_item.location_found}
                table
                  tbody
                    tr
                      td 案内所
                      td = link_to found_item.reception_desk.name, reception_desk_path(found_item.reception_desk.id)
                    tr
                      td 特徴
                      td = found_item.characteristic
                  p = found_item.note
              ._c-card__action
                - if found_item.status?
                  = link_to 'さらに詳しく', found_item,:class => '_c-btn _c-btn--block'
                - else
                  = link_to 'さらに詳しく', found_item,:class => '_c-btn _c-btn--block _c-btn--danger'
      = paginate @found_items

app/views/found_items/new.html.slim
- provide(:title, '拾得物を登録する')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 拾得物を登録する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', found_items_path

app/views/found_items/show.html.slim
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 拾得物情報
    ._c-section__content
      article._c-entry
        header._c-entry__header
          h1._c-entry__title #{@found_item.kind_i18n}
          ul._c-meta
            li._c-meta__item 作成日時 #{@found_item.created_at.strftime("%Y/%m/%d %H:%M")}
            - unless @found_item.created_at == @found_item.updated_at
              li._c-meta__item 更新日時 #{@found_item.updated_at.strftime("%Y/%m/%d %H:%M")}

        ._c-entry__content
          - if @found_item.status?
            ._c-alert._c-alert--success
              strong この拾得物は解決済みです
              h3 = FoundItem.human_attribute_name('resolved_at')
              p = @found_item.resolved_at.strftime("%Y/%m/%d %H:%M")
              - if User.find(@found_item.resolver_id)
                h3 = FoundItem.human_attribute_name('resolver_id')
                p = User.find(@found_item.resolver_id).name
          - else
            ._c-alert._c-alert--danger
              p この拾得物は未解決です
          h2 = FoundItem.human_attribute_name('reception_desk_id')
          p = ReceptionDesk.find(@found_item.reception_desk_id).name
          h2 = FoundItem.human_attribute_name('receptionist_id')
          p = User.find(@found_item.receptionist_id).name
          h2 = FoundItem.human_attribute_name('location_found')
          p = @found_item.location_found
          h2 = FoundItem.human_attribute_name('characteristic')
          p = @found_item.characteristic
          - unless @found_item.finder_name.blank?
            h2 = FoundItem.human_attribute_name('finder_name')
            p = @found_item.finder_name
          - unless @found_item.finder_contact.blank?
            h2 = FoundItem.human_attribute_name('finder_contact')
            p = @found_item.finder_contact
          - unless @found_item.note.blank?
            h2 = FoundItem.human_attribute_name('note')
            p = @found_item.note

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '編集', edit_found_item_path(@found_item)
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', found_items_path