config/routes.rb
Rails.application.routes.draw do
  resources :lost_items
  resources :found_items
  resources :reception_desks
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout" }
  root "pages#index"
end

app/models/lost_item.rb
class LostItem < ApplicationRecord
  before_save :set_resolved_at
  belongs_to :reception_desk
  validates :reception_desk_id, presence: true
  validates :receptionist_id, presence: true
  validates :kind, presence: true
  validates :location_lost, presence: true
  validates :characteristic, presence: true
  validates :status, inclusion: { in: [true, false] }
  validate :check_resolver_id
  enum kind: {
    other: 0,
    key: 1,
    wallet: 2,
    mobile_phone: 3,
    electronic_device: 4,
    clothes: 5,
    card: 6,
    cash: 7,
    card_case: 8,
    keychain: 9,
    umbrella: 10,
    glasses: 11,
  }

  def set_resolved_at
    self.resolved_at = if status
                         Time.now.utc
                       else
                         ""
                       end
  end

  def check_resolver_id
    if self.status && !self.resolver_id
      errors.add(:resolver_id, "を入力してください")
    end
  end
end

app/controllers/lost_items_controller.rb
class LostItemsController < ApplicationController
  before_action :set_lost_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :edit, :create, :update, :destroy, :search]

  # GET /lost_items
  def index
    @lost_item = LostItem.new
    @search = LostItem.ransack(params[:q])
    if params[:q]
      characteristics = params[:q][:characteristic_cont_all].split(/[\p{blank}\s]+/) unless params[:q][:characteristic_cont_all].nil?
      params[:q][:characteristic_cont_all] = characteristics if characteristics
      notes = params[:q][:note_cont_all].split(/[\p{blank}\s]+/) unless params[:q][:note_cont_all].nil?
      params[:q][:note_cont_all] = notes if notes
      @search = LostItem.ransack(params[:q])
      @lost_items = @search.result.order(created_at: :desc).page params[:page]
    else
      @lost_items = LostItem.order(created_at: :desc).page params[:page]
    end

    respond_to do |format|
      format.html
      format.csv do
        @lost_items = LostItem.all
        send_data render_to_string, filename: "lost_items.csv", type: :csv
      end
    end
  end

  # GET /lost_items/1
  def show
  end

  # GET /lost_items/new
  def new
    @lost_item = LostItem.new
  end

  # GET /lost_items/1/edit
  def edit
  end

  # POST /lost_items
  def create
    @lost_item = LostItem.new(lost_item_params)

    if @lost_item.save
      redirect_to lost_items_path, notice: "Lost item was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /lost_items/1
  def update
    if @lost_item.update(lost_item_params)
      redirect_to @lost_item, notice: "Lost item was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /lost_items/1
  def destroy
    @lost_item.destroy!
    redirect_to lost_items_url, notice: "Lost item was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_lost_item
      @lost_item = LostItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lost_item_params
      params.require(:lost_item).permit(:resolver_id, :reception_desk_id,
                                        :receptionist_id, :kind,
                                        :location_lost, :characteristic,
                                        :loser_name, :loser_contact,
                                        :note, :status,
                                        :q)
    end
end

app/helpers/lost_items_helper.rb
module LostItemsHelper
end

app/views/lost_items/_form.html.slim
._c-section__content
  ._c-row._c-row--center
    ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
      = form_for @lost_item do |f|
        ._c-card
          ._c-card__body
            - if @lost_item.errors.any?
              ._c-alert._c-alert--danger
                h3 エラー
                ul._c-meta
                  - @lost_item.errors.full_messages.each do |message|
                    li._c-meta__item = message

            ._c-row__col._c-row__col--1-1
              = f.label :reception_desk_id
              br
              span._c-select data-c="select" aria-selected="false"
                = f.collection_select :reception_desk_id, ReceptionDesk.all, :id, :name
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :receptionist_id
              br
              span._c-select data-c="select" aria-selected="false"
                - if :receptionist_id.blank?
                  = f.collection_select :receptionist_id, User.all, :id, :name, :selected => current_user.id
                - else
                  = f.collection_select :receptionist_id, User.all, :id, :name
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :kind
              br
              span._c-select data-c="select" aria-selected="false"
                = f.select :kind, FoundItem.kinds_i18n.invert
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :location_lost
              br
              = f.text_field :location_lost, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :characteristic
              br
              = f.text_field :characteristic, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :loser_name
              br
              = f.text_field :loser_name, :class => '_c-form-control'
            ._c-row__col._c-row__col--1-1
              = f.label :loser_contact
              br
              = f.text_field :loser_contact, :class => "_c-form-control"
            ._c-row__col._c-row__col--1-1
              = f.label :note
              br
              = f.text_area :note, :class => "_c-form-control"
            hr
            ._c-row__col._c-row__col--1-1
              = f.label :resolver_id
              br
              small 未解決の場合は空白を選択してください。
              br
              span._c-select data-c="select" aria-selected="false"
                = f.collection_select :resolver_id, User.all, :id, :name, :include_blank => true
                span._c-select__label data-c="select__label"
            ._c-row__col._c-row__col--1-1
              = f.label :status
              br
              label
                span._c-radio>
                  = f.radio_button :status, true
                  span._c-radio__control
                | 解決済み
              label
                span._c-radio>
                  = f.radio_button :status, false
                  span._c-radio__control
                | 未解決
          ._c-card__action
            = f.submit :class => "_c-btn _c-btn--block"

app/views/lost_items/edit.html.slim
- provide(:title, '紛失物を編集する')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物を編集する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', lost_items_path

app/views/lost_items/index.html.slim
- provide(:title, '紛失物')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物を登録する
    == render 'form'
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物検索
    ._c-section__content
      ._c-row._c-row--center
        ._c-row__col._c-row__col--1-1._c-row__col--lg-1-2
          = search_form_for @search, url: lost_items_path do |f|
            ._c-card
              ._c-card__body
                ._c-row__col._c-row__col--1-1
                  = f.label :status_eq, "状態"
                  br
                  label
                    span._c-radio>
                      = f.radio_button :status_eq, true
                      span._c-radio__control
                    | 解決済み
                  label
                    span._c-radio>
                      = f.radio_button :status_eq, false
                      span._c-radio__control
                    | 未解決
                ._c-row__col._c-row__col--1-1
                  = f.label :reception_desk_id_eq, "受付案内所"
                  br
                    span._c-select data-c="select" aria-selected="false"
                      = f.collection_select :reception_desk_id_eq, ReceptionDesk.all, :id, :name, :include_blank => true
                      span._c-select__label data-c="select__label"
                ._c-row__col._c-row__col--1-1
                  = f.label :kind_eq, "種別"
                  br
                  span._c-select data-c="select" aria-selected="false"
                    = f.select :kind_eq, LostItem.kinds_i18n.invert.map {|key, value| [key, FoundItem.kinds[value]]}, :include_blank => true
                    span._c-select__label data-c="select__label"
                ._c-row__col._c-row__col--1-1
                  = f.label :characteristic_cont_all, "特徴"
                  br
                    = f.search_field :characteristic_cont_all, :class => '_c-form-control'
                ._c-row__col._c-row__col--1-1
                  = f.label :note_cont_all, "備考"
                  br
                    = f.search_field :note_cont_all, :class => '_c-form-control'
              ._c-card__action
                = f.submit '検索', :class => "_c-btn _c-btn--block"
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物一覧
    ._c-section__content
      ul._c-meta
        - unless @lost_items.total_count == 0
          li._c-meta__item #{@lost_items.total_count}件の紛失物情報が見つかりました。
          li._c-meta__item = link_to "CSVダウンロード", lost_items_path(format: "csv")
        - else
          li._c-meta__item 紛失物情報が見つかりませんでした。
      ._c-row._c-row--margin
        - @lost_items.each do |lost_item|
          ._c-row__col._c-row__col--1-1._c-row__col--md-1-2._c-row__col--lg-1-4
            ._c-card
              ._c-card__body
                h1 #{lost_item.kind_i18n}
                small 紛失場所 #{lost_item.location_lost}
                table
                  tbody
                    tr
                      td 案内所
                      td = link_to lost_item.reception_desk.name, reception_desk_path(lost_item.reception_desk.id)
                    tr
                      td 特徴
                      td = lost_item.characteristic
                  p = lost_item.note
              ._c-card__action
                - if lost_item.status?
                  = link_to 'さらに詳しく', lost_item, :class => '_c-btn _c-btn--block'
                - else
                  = link_to 'さらに詳しく', lost_item, :class => '_c-btn _c-btn--block _c-btn--danger'
      = paginate @lost_items

app/views/lost_items/new.html.slim
- provide(:title, '紛失物を登録する')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物を登録する
    == render 'form'

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', lost_items_path

app/views/lost_items/show.html.slim
- provide(:title, '紛失物情報')
section._c-section._c-section--bg
  ._c-container
    h2._c-section__title 紛失物情報
    ._c-section__content
      article._c-entry
        header._c-entry__header
          h1._c-entry__title #{@lost_item.kind_i18n}
          ul._c-meta
            li._c-meta__item 作成日時 #{@lost_item.created_at.strftime("%Y/%m/%d %H:%M")}
            - unless @lost_item.created_at == @lost_item.updated_at
              li._c-meta__item 更新日時 #{@lost_item.updated_at.strftime("%Y/%m/%d %H:%M")}

        ._c-entry__content
          - if @lost_item.status?
            ._c-alert._c-alert--success
              strong この紛失物は解決済みです
              h3 = LostItem.human_attribute_name('resolved_at')
              p = @lost_item.resolved_at.strftime("%Y/%m/%d %H:%M")
              - if User.find(@lost_item.resolver_id)
                h3 = LostItem.human_attribute_name('resolver_id')
                p = User.find(@lost_item.resolver_id).name
          - else
            ._c-alert._c-alert--danger
              p この紛失物は未解決です
          h2 = LostItem.human_attribute_name('reception_desk_id')
          p = ReceptionDesk.find(@lost_item.reception_desk_id).name
          h2 = LostItem.human_attribute_name('receptionist_id')
          p = User.find(@lost_item.receptionist_id).name
          h2 = LostItem.human_attribute_name('location_lost')
          p = @lost_item.location_lost
          h2 = LostItem.human_attribute_name('characteristic')
          p = @lost_item.characteristic
          - unless @lost_item.loser_name.blank?
            h2 = LostItem.human_attribute_name('loser_name')
            p = @lost_item.loser_name
          - unless @lost_item.loser_contact.blank?
            h2 = LostItem.human_attribute_name('loser_contact')
            p = @lost_item.loser_contact
          - unless @lost_item.note.blank?
            h2 = LostItem.human_attribute_name('note')
            p = @lost_item.note

    ul._c-navbar
      li._c-navbar__item data-c="navbar__item"
        = link_to '編集', edit_lost_item_path(@lost_item)
      li._c-navbar__item data-c="navbar__item"
        = link_to '戻る', lost_items_path