config/routes.rb
Rails.application.routes.draw do
  resources :lost_items
  resources :found_items
  resources :reception_desks
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout" }
  root "pages#index"
end

app/views/layouts/_footer.html.slim
footer#footer._l-footer data-l="footer"
  ._c-container
    ._c-row._c-row--margin
      ._c-row__col._c-row__col--1-1._c-row__col--lg-2-4
        ._c-site-branding
          h1._c-site-branding__title au-system17
      ._c-row__col._c-row__col--1-1._c-row__col--lg-2-4
        nav.p-footer-nav
          ._c-row._c-row--margin._c-row--right
            ._c-row__col._c-row__col--1-1._c-row__col--md-1-3
              ul.p-footer-nav__list
                li.p-footer-nav__item
                  - if user_signed_in?
                    = link_to 'ログアウト', destroy_user_session_path
                  - else
                    = link_to 'ログイン', new_user_session_path
                - if user_signed_in?
                  li.p-footer-nav__item
                    = link_to 'アカウント設定', edit_user_registration_path
                - else
                  li.p-footer-nav__item
                    = link_to '新規登録', new_user_registration_path
            - if user_signed_in?
              ._c-row__col._c-row__col--1-1._c-row__col--md-1-3
                ul.p-footer-nav__list
                  li.p-footer-nav__item
                    = link_to '案内所を登録する', new_reception_desk_path
                  li.p-footer-nav__item
                    = link_to '拾得物を登録する', new_found_item_path
                  li.p-footer-nav__item
                    = link_to '紛失物を登録する', new_lost_item_path
  ._c-copyright
    ._c-container
      = link_to '筑波大学 学園祭実行委員会', 'https://www.sohosai.tsukuba.ac.jp/'

app/views/layouts/_hamburger.html.slim
._c-hamburger-btn._u-hidden-lg data-c="drawer-btn" aria-expanded="false" aria-controls="drawer-nav"
  ._c-hamburger-btn__bar
  ._c-hamburger-btn__bar
  ._c-hamburger-btn__bar

app/views/layouts/_page_effect.html.slim
._c-page-effect data-c="page-effect" data-page-effect="fadein" aria-hidden="true"
  ._c-page-effect__item
    ._c-spinner-circle

app/views/layouts/application.html.slim
doctype html
html lang="ja" data-sticky-footer="true" data-scrolled="true"
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    title = full_title(yield(:title))
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet"
    = javascript_include_tag 'application'

  body._l-body
    = render partial: 'layouts/page_effect'
  ._c-drawer data-c="drawer"
    nav#drawer-nav._c-drawer__body._c-drawer__body--fixed data-c="drawer__body" role="navigation" aria-hidden="true"
      ul._c-drawer__menu
        - if user_signed_in?
          li._c-drawer__item
            = link_to '案内所一覧', reception_desks_path
          li._c-drawer__item
            = link_to '拾得物', found_items_path
          li._c-drawer__item
            = link_to '紛失物', lost_items_path

    #container._l-container data-l="container"
      header#header._l-header data-l="header" data-l-header-type="sticky" role="banner"
        ._c-container
          ._c-row._c-row--nowrap._c-row--lg-margin._c-row--middle
            ._c-row__col._c-row__col--auto
              ._c-site-branding
                = link_to "au-system17", root_path, class: "_c-site-branding__title"

            ._c-row__col._c-row__col--auto._u-hidden-sm._u-hidden-md
              ._u-pull-right
                nav.p-global-nav role="navigation"
                  ul._c-navbar._c-navbar--auto
                    - if user_signed_in?
                      li._c-navbar__item data-c="navbar__item"
                        = link_to '案内所一覧', reception_desks_path
                      li._c-navbar__item data-c="navbar__item"
                        = link_to '拾得物', found_items_path
                      li._c-navbar__item data-c="navbar__item"
                        = link_to '紛失物', lost_items_path

          = render partial: 'layouts/hamburger'

      #contents._l-contents data-l="contents"
        main#main._l-main role="main"
        - unless notice.nil?
          p._c-alert._c-alert--info = notice
        - unless alert.nil?
          p._c-alert._c-alert--danger = alert
        = yield

      = render partial: 'layouts/footer'
  = javascript_include_tag "app.js"
  script src="https://www.googletagmanager.com/gtag/js?id=UA-109160119-1" async=true
  javascript:
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-109160119-1');